<script setup lang="ts">
/**
 * @component EnvironmentCollectionRequests
 * @description Lists the saved requests of the active collection and loads a
 * chosen one into a request tab. Saved requests are typically generated by
 * tooling to pre-fill an API flow (e.g. a registration sequence) so the whole
 * flow is one click away from running.
 */
import { AppButton } from '@/components/base/button';
import HttpVerbLabel from '@/components/domain/HttpVerbLabel/HttpVerbLabel.vue';
import { type SavedRequest, useEnvironmentVariablesStore, useTabsStore } from '@/stores';
import { SendIcon } from 'lucide-vue-next';
import { computed } from 'vue';
import { useRouter } from 'vue-router';

const environmentVariablesStore = useEnvironmentVariablesStore();
const tabsStore = useTabsStore();
const router = useRouter();

const requests = computed<SavedRequest[]>(
    () => environmentVariablesStore.activeCollection?.requests ?? [],
);

const openRequest = (request: SavedRequest) => {
    tabsStore.restoreFromSharedPayload(request);
    router.push({ name: 'main' });
};
</script>

<template>
    <div v-if="requests.length" class="mt-4" data-testid="collection-requests">
        <div class="mb-1.5">
            <h3 class="text-sm font-semibold">Requests</h3>
            <p class="text-subtle-foreground text-xs leading-tight">
                Pre-filled requests for this flow. Open one to load it into a tab, then
                send it.
            </p>
        </div>

        <ul class="flex flex-col gap-1">
            <li
                v-for="request in requests"
                :key="request.id"
                class="p-panel hover:bg-subtle flex items-center gap-2 rounded border text-sm"
                data-testid="collection-request-item"
            >
                <HttpVerbLabel :method="request.method.toUpperCase()" />
                <div class="min-w-0 flex-1 leading-tight">
                    <div class="truncate font-medium">{{ request.name }}</div>
                    <div class="text-subtle-foreground truncate font-mono text-xs">
                        {{ request.endpoint }}
                    </div>
                </div>
                <AppButton
                    variant="ghost"
                    size="xs"
                    data-testid="open-request-btn"
                    @click="openRequest(request)"
                >
                    <SendIcon />
                    Open
                </AppButton>
            </li>
        </ul>
    </div>
</template>
