name: run-js-tests

on:
  pull_request:
  push:
    branches: [ base ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            js:
              - '**.ts'
              - '**.js'
              - '.github/workflows/js-tests.yml'
              - 'package.json'
              - 'package-lock.json'

      - name: Setup Node.js
        if: steps.filter.outputs.js == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: steps.filter.outputs.js == 'true'
        run: npm ci

      - name: Run tests
        if: steps.filter.outputs.js == 'true'
        run: npm run test

