name: phpstan

on:
  push:
    branches: [ base ]
  pull_request:

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            phpstan:
              - '**.php'
              - 'tools/phpstan/phpstan.neon.dist'
              - '.github/workflows/phpstan.yml'
              - 'composer.json'
              - 'composer.lock'

      - name: Setup PHP
        if: steps.filter.outputs.phpstan == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        if: steps.filter.outputs.phpstan == 'true'
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        if: steps.filter.outputs.phpstan == 'true'
        run: composer phpstan
