name: run-types-check

on:
  push:
    branches: [ base ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: TS Types Checks

    steps:
      - name: Checkout code
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            types:
              - '**.ts'
              - '**.js'
              - '.github/workflows/types-check.yml'
              - 'package.json'
              - 'package-lock.json'

      - name: Setup Node.js
        if: steps.filter.outputs.types == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: steps.filter.outputs.types == 'true'
        run: npm ci --ignore-scripts

      - name: Run Type Checks
        if: steps.filter.outputs.types == 'true'
        run: npm run type:check

